default: &default
  #adapter: postgresql
  adapter: mysql2
  ecoding: utf-8
  # encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>

development:
  <<: *default
  database: Autonoma_development
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>
  port:     <%= ENV['BD_LOCAL_PORT'] %>
  host:     <%= ENV['BD_LOCAL_HOST'] %>
  #pool: 5
  timeout:  <%= ENV['BD_LOCAL_TIMEOUT'] %>
  ecoding:  <%= ENV['BD_LOCAL_ECODING'] %>

test:
  <<: *default
  database: Autonoma_test
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>
  port:     <%= ENV['BD_LOCAL_PORT'] %>
  host:     <%= ENV['BD_LOCAL_HOST'] %>
  #pool: 5
  timeout:  <%= ENV['BD_LOCAL_TIMEOUT'] %>
  ecoding:  <%= ENV['BD_LOCAL_ECODING'] %>

production:
  #adapter: postgresql
  ecoding: utf-8
  pool:    <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: Autonoma_production
  username: Autonoma
  password: <%= ENV['AUTONOMA_DATABASE_PASSWORD'] %>
